# Generated by Django 4.2.6 on 2023-11-01 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Flowers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='flower/')),
                ('size', models.CharField(choices=[(1, 'X'), (2, 'S'), (3, 'M'), (4, 'L')], max_length=2)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Flowers.type')),
            ],
        ),
    ]
