# Generated by Django 4.2.6 on 2023-11-01 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Flowers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flowers',
            options={'verbose_name': 'Flower', 'verbose_name_plural': 'Flowers'},
        ),
    ]
