# Generated by Django 4.2.6 on 2023-11-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flowers', '0002_alter_flowers_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowers',
            name='image',
            field=models.URLField(max_length=1000),
        ),
    ]
