# Generated by Django 4.2.6 on 2023-11-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flowers', '0003_alter_flowers_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowers',
            name='discount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='flowers',
            name='size',
            field=models.CharField(choices=[('X', 'X'), ('S', 'S'), ('M', 'M'), ('L', 'L')], max_length=2),
        ),
    ]
